spring:
  application:
    name: n-user-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5432/n-user-service
    username: postgres
    password: mitrandir
jwt:
  key: Nikon1234
  expiration: 3600000
  bearer: 'Bearer '
  begin-index: 7
server:
  port: 8081
security:
  encoder:
    strength: 12