spring:
  application:
    name: n-user-service
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        generate_statistics: false
    hibernate:
      ddl-auto: validate
    open-in-view: true
  mail:
    host: smtp.gmail.com
    username: hsciapan@gmail.com
    password: "crzhhhizdfvljrld"
    admin-mail: hirrafes@gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            trust: smtp.gmail.com
  datasource:
    url: jdbc:postgresql://localhost:5432/n-user-service
    username: postgres
    password: mitrandir

jwt:
  key: Nikon1234
  expiration: 3600000
  bearer: 'Bearer '
  begin-index: 7

server:
  port: 8081
  domain: http://localhost:8081/

security:
  encoder:
    strength: 12