create table users
(
    id         bigint generated by default as identity,
    role       smallint check (role between 0 and 2),
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    primary key (id)
)