create table users
(
    id         bigint generated by default as identity,
    role       varchar(255) not null,
    email      varchar(255) unique not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    password   varchar(255) not null,
    primary key (id)
)