create table users
(
    is_active         boolean      not null,
    is_email_verified boolean      not null,
    id                bigint generated by default as identity,
    email             varchar(255) not null unique,
    first_name        varchar(255) not null,
    last_name         varchar(255) not null,
    password          varchar(255) not null,
    role              varchar(255) not null,
    primary key (id)
);
create table activation_code
(
    expired_at timestamp(6) not null,
    id         bigint generated by default as identity,
    user_id    bigint       not null,
    code       varchar(255) not null,
    primary key (id)
)